### ISSUE TITLE
Crear Acciones para todas las entidades

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [davimontr/WebFacturas#17]
Necesitamos definir interfaces y clases que las implementen para todas las entidades de la base de datos

**Comment by kenneth-bolivar-castro** [comment]
Como estamos en esta tarea? @OlgerAndres @davimontr

**Comment by OlgerAndres** [comment]
La acción de roles,esta finalizada.

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres @davimontr agreguen el estatus aqui.

**Comment by davimontr** [comment]
Métodos de cada entidad listos

**Comment by kenneth-bolivar-castro** [comment]
@davimontr podemos cerrar este ticket, verdad?

**Comment by OlgerAndres** [comment]
Esta listo las entidades.
