### ISSUE TITLE
Agregar diseño para las paginas

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [davimontr/WebFacturas#18]
Necesitamos tener un diseño para el sitio.
Revise como implementar http://getbootstrap.com/

**Comment by Blackcheater** [comment]
Ok comenzaré de una vez

**Comment by kenneth-bolivar-castro** [comment]
@Blackcheater he creado un maestro y una pagina para el dashboard que es la pagina principal de administracion,
![dashboard](https://user-images.githubusercontent.com/3356086/31051084-50e192d0-a61c-11e7-9312-81aa8af0adaf.PNG)

En la pagina principal Default.aspx esta el link para el dashboard.
![captura](https://user-images.githubusercontent.com/3356086/31051093-7793cde4-a61c-11e7-817f-0e1ef29c896f.PNG)
