### ISSUE TITLE
Documentacion 

### ISSUE THREAD

**Issue by OlgerAndres** [davimontr/WebFacturas#19]
Manual de usuario  y lo usaremos como el manual de ayuda dentro de la aplicación.

**Comment by kenneth-bolivar-castro** [comment]
Modelo UML sobre las tareas que tenemos y el reporte de @OlgerAndres sobre los detalles del cliente

**Comment by Blackcheater** [comment]
Tareas pendientes 
#2 
#3 
#4 
#5 
#20 
#21 
#22

**Comment by OlgerAndres** [comment]
Por hacer 👍 
 Manual de usuario.

**Comment by kenneth-bolivar-castro** [comment]
Listo
