### ISSUE TITLE
Requerimientos especificos del cliente

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [davimontr/WebFacturas#22]
Necesitamos los requerimientos del cliente para lograr generar el proyecto en base a lo que se solicita.

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres hasta la fecha tenemos esto
https://user-images.githubusercontent.com/3356086/31051084-50e192d0-a61c-11e7-9312-81aa8af0adaf.PNG

Y estamos trabajando en un demo para mostrar #23

**Comment by Blackcheater** [comment]
![modulo facturacion](https://user-images.githubusercontent.com/32321426/31260386-bb148b02-aa0a-11e7-950b-45240dd52c32.png)

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres definir los alcances para completar el sistema, buscando algo simple para tener el cumplimiento y cerrar en fechas correctas.
Evitar mezclar las cobranzas para no extender el producto, negocie con el cliente.

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres completo!
