### ISSUE TITLE
Cierre de caja

### ISSUE THREAD

**Issue by OlgerAndres** [davimontr/WebFacturas#31]
Incluir reportes,que sume el total de ventas, calcular el monto gravado y el monto exento, mostrar cuanto se recibió en colones,dolares, euros.

**Comment by kenneth-bolivar-castro** [comment]
Documentacion: https://www.numier.com/docs/como-hacer-un-cierre-de-caja/
Video: https://youtu.be/SonVwtXpNH0

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres como estamos aqui?

**Comment by kenneth-bolivar-castro** [comment]
los reportes ventas brutas del dia ,categorizado por departamento y dentro de departamento el código del producto , ya sumado, además de cuánto  fue la recaudación bruta  en cada producto, cual se debe incluir cuentas en colones,euros,dólares y tarjetas,especificar  tasa de cambio del dia  si se pago con dolares o euros, la sumatoria de las monedas de colones,dólares, euros y tarjetas va ser igual a la sumatoria bruta de caja, en el cierre de caja.
Tomar en cuenta que a la hora de la sumatoria de la ventas contra cajas,puede haber un pequeño margen de error, a cobrar o digitar un producto.
 Reporte de cuanto fue por gravado y cuanto por excento, solo hay una posibilidad de las 2, ademas que la sumatoria debe ser igual al monto bruto.
En el monto gravado, hay una  columna de  del monto del impuesto recaudado

**Comment by kenneth-bolivar-castro** [comment]
Reporta general y exportaciones listas.

**Comment by kenneth-bolivar-castro** [comment]
Analisis e implementacion de los detalles requeridos.

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres puede comprar que esten todos los datos que se solicitan, por favor

**Comment by kenneth-bolivar-castro** [comment]
listo
