### ISSUE TITLE
Implementar el tipo de moneda 

### ISSUE THREAD

**Issue by OlgerAndres** [davimontr/WebFacturas#36]
1.Colones
2. Dolares
3. Euros
4. Tarjetas
En el  formulario de facturación y en el cierre de caja.

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres cierre de caja NO ocupa este valor en absoluto.

**Comment by kenneth-bolivar-castro** [comment]
Creadas tablas "FormaPago" y "TipoMoneda"
