### ISSUE TITLE
Implementar la ventas gravadas y excentas

### ISSUE THREAD

**Issue by OlgerAndres** [davimontr/WebFacturas#37]
A la hora de cierre de caja se debe especificar cuales de  las ventas son gravadas o exentas

**Comment by kenneth-bolivar-castro** [comment]
El reporte de cierre de cajas debe sacar esos valores de la base de datos. Voy a incluirlo en la tabla de productos. @OlgerAndres

**Comment by kenneth-bolivar-castro** [comment]
Integrado dentro de tabla productos.
