### ISSUE TITLE
Capa Presentacion

### ISSUE THREAD

**Issue by davimontr** [davimontr/WebFacturas#4]
Etiqueta principal para la capa presentecion

**Comment by kenneth-bolivar-castro** [comment]
Tareas pendientes
**#10** completa
**#14** completa
**#15** completo
**#18** completa
**#25** completo
**#26** COmpleto

**Comment by kenneth-bolivar-castro** [comment]
Me estoy asignando este ticket global para trabajar sobre toda la capa de presentacion

**Comment by kenneth-bolivar-castro** [comment]
Menu actualizado,
![menu](https://user-images.githubusercontent.com/3356086/31305277-28d56948-aaf3-11e7-9efa-95593f4d565d.PNG)

@OlgerAndres @davimontr @Blackcheater los menus fueron actualizados.

**Comment by kenneth-bolivar-castro** [comment]
Vista del sitio web,
![dise o](https://user-images.githubusercontent.com/3356086/32409685-020ffbcc-c176-11e7-834b-85e03baf1523.PNG)

**Comment by kenneth-bolivar-castro** [comment]
listo
