### ISSUE TITLE
Consumir Banco Central - Tipo Cambios

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [davimontr/WebFacturas#45]
Obtener los tipos de cambio de la fecha en el banco central cada vez que se inicie la sesion.

**Comment by OlgerAndres** [comment]
https://www.youtube.com/watch?v=yKwyhUruFc8

@kenneth-bolivar-castro esto me servirá ?

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres eso explica como hacer el WebService, pero nosotros ocupamos consumirlo, puede que en la parte de consumir del video funcione para nosotros, revise apartir del min 13 segundo 15,
https://youtu.be/yKwyhUruFc8?t=13m15s

**Comment by kenneth-bolivar-castro** [comment]
Listo
