### ISSUE TITLE
Revision Azure

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [davimontr/WebFacturas#47]
Revisar Todo el sitio

**Comment by davimontr** [comment]
- [x] Definir Vuelto
- [x] Agregar precio unitario en productos.aspx
- [x] Incluir precio unitario productos en reportes
- [x] Mostrar facturas y fechas en reporte grafico
- [x] Agregar calendario en reporte grafico(quitar textbox)
- [x] Revisar cierre de cajas 
- [x] Agregar formato a números en reportes
- [x] Facturación: eliminar convertido en moneda colones.
- [x] Mostrar el campo de roles solo cuando es administrador.
- [x] Definir la pagina de error de permisos y pagina no encontrada
- [x] Definir la hora adecuada en Azure
- [x]  Implementar el manual en el proyecto.
- [x] Agregar facturas de credito.
- [x] Agregar creditos a cierre de cajas.

**Comment by kenneth-bolivar-castro** [comment]
listo
