### ISSUE TITLE
Objetos de la base de datos

### ISSUE THREAD

**Issue by davimontr** [davimontr/WebFacturas#5]
Etiqueta principal para los objetos de la base de datos(store procedure, funtions, views y triggers)

**Comment by davimontr** [comment]
revisar la estructura de la base de datos @kenneth-bolivar-castro #6

**Comment by kenneth-bolivar-castro** [comment]
Tareas pendientes
**#11** completa
**#12** completa
**#13** completa
**#27** completa 
**#28** completa
**#29** completa
**#30** completa

**Comment by kenneth-bolivar-castro** [comment]
Diagrama de base de datos
![screenshot from 2017-09-29 00-17-29](https://user-images.githubusercontent.com/3356086/31003242-dd198c16-a4ab-11e7-90f4-b92029adac81.png)

- Cada "**Usuario**" tiene un "**Rol**" asignado para definir permisos.
- Los "**Productos**" tienen un "**Proveedor**" relacionado.
- El costo de un "**Producto**" se calcula en tiempo de ejecucion en base al "**costo**" por la "**utilidad**" y agregando el "**impuesto**" (Se define como entero y se divide entre 100).
- Los "**Articulos**" tienen un unico "**Producto**", entonces N "**Articulos**" pueden estar relacionados a una unica "**Factura**"
- El valor de cada "**Articulo**" se calcula en base al precio real del "**Producto**" por la "**cantidad**".
- El valor de las "**Facturas**" es la suma del total de los "**Articulos**" relacionados e igual se le puede aplicar el "**descuento**" (Que se expresa como entero pero se divide entre 100).
- Cada "**Factura**" solo tiene un unico "**Cliente**" relacionado.

CC: @davimontr @OlgerAndres @Blackcheater

**Comment by OlgerAndres** [comment]
Llevar un control del registro de las compras y de cuales productos son los mas vendidos y la sumatoria de estos @kenneth-bolivar-castro #12

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres @davimontr @Blackcheater 
Siendo mi responsabilidad los objetos en la base de datos, vamos a necesitar que todos tengamos como nombre de la instancia de SQL igual a "localhost" entonces, sera mas sencillo para @davimontr configurar la conexion por medio del metodo SQL.

- Go to SQl Server Configuration Manager
-  Open SQL Server Network Configuration
-  Click on my Named Instance
-  Open TCP/IP
-  Click on IP addresses
-  Added port 1433 to all ip's

![mmwgo](https://user-images.githubusercontent.com/3356086/31049181-0b4d49c0-a5eb-11e7-9714-86b972ee0997.png)

**Comment by kenneth-bolivar-castro** [comment]
@davimontr ud logro configurar el localhost?

**Comment by kenneth-bolivar-castro** [comment]
Modificar nombre de la tabla de **Articulos** por **LineaArticulo**

**Comment by kenneth-bolivar-castro** [comment]
@OlgerAndres @davimontr @Blackcheater la tabla de **Articulos** de cambio a **LineaArticulo**

**Comment by kenneth-bolivar-castro** [comment]
Diagrama actualizado a la fecha,
![diagrama](https://user-images.githubusercontent.com/3356086/31752046-2a915894-b446-11e7-8d11-fb484fbbb22b.PNG)

**Comment by Blackcheater** [comment]
va a ver alguna modificacion de Dicha base de datos?

**Comment by kenneth-bolivar-castro** [comment]
listo
