### ISSUE TITLE
Revisar La Estructura de la Base de Datos

### ISSUE THREAD

**Issue by davimontr** [davimontr/WebFacturas#6]
Revise que se puede modificar, agregar o eliminar

**Comment by kenneth-bolivar-castro** [comment]
@davimontr he actualizado la base de datos,
https://github.com/davimontr/WebFacturas/blob/master/script.sql

CC: @OlgerAndres @Blackcheater

**Comment by kenneth-bolivar-castro** [comment]
Los totales se calculan en tiempo de ejecucion, eventualmente voy a crear vistas para verlo por medio de funciones.
