### ISSUE TITLE
Crear conexión entre base de datos y proyecto

### ISSUE THREAD

**Issue by davimontr** [davimontr/WebFacturas#7]
crear la conexión a la base de datos utilizando el método de login

**Comment by kenneth-bolivar-castro** [comment]
@davimontr para crear el nuevo login, generar un nuevo usuario y relacionarlos con la base de datos, se debe ejecutar lo siguiente:
```
USE [master]
GO
CREATE LOGIN [UACA] WITH PASSWORD=N'340$Uuxwp7Mcxo7Khy' MUST_CHANGE, DEFAULT_DATABASE=[Facturacion], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
USE [Facturacion]
GO
CREATE USER [UACA] FOR LOGIN [UACA]
GO
USE [Facturacion]
GO
ALTER ROLE [db_owner] ADD MEMBER [UACA]
GO
```
Entonces, con esto ya puedes hacer una nueva conexion y todos nosotros vamos a tener el mismo ambiente para ejecutarlo.

CC: @OlgerAndres @Blackcheater

**Comment by kenneth-bolivar-castro** [comment]
Cuando hacen eso por favor intentan iniciar abrir una conexion con el nuevo usuario y revisar que puedan ver la base de datos,
![captura](https://user-images.githubusercontent.com/3356086/31049329-39c947d8-a5ee-11e7-84b2-a6ab593adefc.PNG)

La primera vez, le pediran actualizar la clave, entonces, pongan exactamente la misma clave.
@OlgerAndres @davimontr @Blackcheater

**Comment by davimontr** [comment]
No me queda clara la clave Kenneth

**Comment by kenneth-bolivar-castro** [comment]
@davimontr exactamente a que se refiere? tiene algun problema?

**Comment by kenneth-bolivar-castro** [comment]
@davimontr despues de ejecutar el codigo SQL al hacer la prueba para conectarse, seguramente le pregunta para cambiar la clave, entonces, pone la misma clave:
`340$Uuxwp7Mcxo7Khy`
Si logra leer el Query ahi dice eso como clave.

**Comment by OlgerAndres** [comment]
![jhgfdsa](https://user-images.githubusercontent.com/31995428/31050535-3b5437ea-a60a-11e7-888a-251aae29d42d.png)

Click derecho sobre el localhost y le dan propiedades.

Si tienen el sql server con autentificador de windows cambiarlo a  ambos como se muestra la imagen,para que se pueden iniciar usuario, recordar la contraseña que esta en gitbuh.

**Comment by kenneth-bolivar-castro** [comment]
@davimontr @OlgerAndres como estamos aquí?
Si ambos tienen configurado como se necesita, estamos bien y cerramos este ticket, sino estamos atrasados una semana.

**Comment by kenneth-bolivar-castro** [comment]
Todos estamos funcionales aqui.
