### ISSUE TITLE
Mapear base de datos 

### ISSUE THREAD

**Issue by davimontr** [davimontr/WebFacturas#8]
Utilizar entity framework

**Comment by kenneth-bolivar-castro** [comment]
@davimontr actualice la base de datos en su local en base al respado existen.
He cambiado la estructura.
https://github.com/davimontr/WebFacturas/issues/5#issuecomment-333042167

**Comment by kenneth-bolivar-castro** [comment]
@davimontr mira lo que he encontrado aqui sobre como generar las entidades utilizando EF
http://www.entityframeworktutorial.net/EntityFramework5/create-dbcontext-in-entity-framework5.aspx

**Comment by kenneth-bolivar-castro** [comment]
@davimontr esta tarea esta lista
